"""Check the facts the battle picker reads out of the client's own tables.

These are generated by `scripts/build_game_data.py`, so what is pinned here is the shape the picker relies on
rather than any particular card. A game patch that changes the shape should fail this, not surprise a run.
"""

import sys
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from src.en.game_battle import (  # noqa: E402
    ATTRIBUTES, CARD_CATEGORY, CARD_COST, CARD_OWNER, CARD_SPARKABLE, CARD_TARGET,
    COMBATANT_ATTRIBUTE, COMBATANT_EGO_CARD, COMBATANT_EGO_COST, COMBATANT_SPARK_CARDS, X_COST,
)
from src.en.game_data import COMBATANTS  # noqa: E402

# The five attributes a player is shown. The client stores each as a colour and names it in its own table.
EXPECTED_ATTRIBUTES = {"Instinct", "Justice", "Order", "Passion", "Void"}
# The kinds of card the client defines. A Curse or a Status Ailment is dealt to you rather than chosen.
EXPECTED_CATEGORIES = {"ATK", "SKILL", "POWER", "ABNORM", "CURSE"}
# The dearest fixed price in the data. `X_COST` comes from the module under test, since what it stands for
# is the generator's to decide.
MOST_EXPENSIVE = 9


class TestAttributes(unittest.TestCase):
    """The attribute table, which is what ties a card to the weakness an enemy shows."""

    def test_all_five_attributes_are_present(self):
        self.assertEqual(set(ATTRIBUTES.values()), EXPECTED_ATTRIBUTES)

    def test_colours_are_distinct(self):
        self.assertEqual(len(ATTRIBUTES), len(set(ATTRIBUTES.values())))

    def test_every_combatant_attribute_is_a_real_one(self):
        self.assertLessEqual(set(COMBATANT_ATTRIBUTE.values()), EXPECTED_ATTRIBUTES)

    def test_the_released_roster_is_covered(self):
        # Every combatant a run can field, with no exceptions - a name the dump has not caught up with yet
        # would leave the picker guessing at that combatant's attribute for a whole run.
        self.assertEqual(set(), set(COMBATANTS) - set(COMBATANT_ATTRIBUTE))


class TestCards(unittest.TestCase):
    """The per-card tables the planner scores a hand with."""

    def test_the_card_tables_describe_the_same_cards(self):
        self.assertEqual(set(CARD_COST), set(CARD_CATEGORY))
        self.assertEqual(set(CARD_COST), set(CARD_TARGET))

    def test_costs_are_in_range(self):
        for name, cost in CARD_COST.items():
            with self.subTest(card=name):
                self.assertTrue(cost == X_COST or 0 <= cost <= MOST_EXPENSIVE)

    def test_most_cards_cost_two_or_less(self):
        # The game hands out three Action Points a turn, so a deck of dearer cards would mean the reading is
        # of something other than Action Points - which is exactly what Ego skills looked like before they
        # were split out.
        cheap = sum(1 for cost in CARD_COST.values() if 0 <= cost <= 2)
        self.assertGreater(cheap, len(CARD_COST) * 0.9)

    def test_categories_are_known(self):
        self.assertEqual(set(CARD_CATEGORY.values()), EXPECTED_CATEGORIES)

    def test_sparkable_cards_are_cards(self):
        self.assertLessEqual(CARD_SPARKABLE, set(CARD_COST))

    def test_no_card_name_starts_with_a_digit(self):
        # A leading digit on a reading is therefore always the hotkey bleeding into the name box, which is
        # what lets `cards.canonical` strip it.
        leading = sorted(name for name in CARD_COST if name[:1].isdigit())
        self.assertEqual(leading, [])


class TestOwnership(unittest.TestCase):
    """The card-to-combatant link, which is where a card gets its attribute from."""

    def test_every_owner_is_a_known_combatant(self):
        self.assertLessEqual(set(CARD_OWNER.values()), set(COMBATANT_ATTRIBUTE))

    def test_owned_cards_are_cards(self):
        self.assertLessEqual(set(CARD_OWNER), set(CARD_COST))

    def test_a_shared_card_goes_to_the_released_combatant(self):
        # Anika has not been released and lists four of Magna's cards. Whoever holds a card in a real run is
        # whose attribute it carries, so the tie has to fall the same way every time the data is rebuilt.
        for cards in COMBATANT_SPARK_CARDS.values():
            for card in cards:
                owner = CARD_OWNER.get(card)
                with self.subTest(card=card):
                    self.assertIn(owner, COMBATANT_ATTRIBUTE)


class TestEgoSkills(unittest.TestCase):
    """Ego skills, which are priced in EP and must not be mistaken for cards."""

    def test_no_ego_skill_is_priced_as_a_card(self):
        self.assertEqual(set(COMBATANT_EGO_CARD.values()) & set(CARD_COST), set())

    def test_every_ego_skill_has_a_cost(self):
        self.assertEqual(set(COMBATANT_EGO_CARD), set(COMBATANT_EGO_COST))

    def test_ego_costs_are_positive(self):
        for combatant, cost in COMBATANT_EGO_COST.items():
            with self.subTest(combatant=combatant):
                self.assertGreater(cost, 0)

    def test_a_known_combatant_reads_correctly(self):
        # One real reading, so a rebuild that quietly empties a table cannot pass on shape alone.
        self.assertEqual(COMBATANT_ATTRIBUTE["Nia"], "Instinct")
        self.assertEqual(COMBATANT_EGO_CARD["Nia"], "Rock and Roll")


if __name__ == "__main__":
    unittest.main()
