"""Generate `src/en/game_data.py` from the game's own English localization table.

The Global client ships its text as `text/en/text.json`, a flat list of `{"id", "text"}` rows. That is the
authoritative source for card, equipment and combatant names, so the settings can offer real pick-lists
instead of asking the user to type a name and hope it matches.

Point `--dump` at the extracted `output` directory of a CZN asset rip. The dump itself is not committed - the
generated module is, so the repo stays self-contained and a game patch is a re-run rather than a mystery.

Run `python scripts/build_game_data.py --dump <path-to-output>`.
"""

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "src" / "en" / "game_data.py"
DEFAULT_DUMP = Path(r"C:\Users\steve1316\Downloads\CZNRipper\output")

# Namespaces in the localization table, and the constant each becomes.
GROUPS = [
    ("CARDS", r"card@name@", "Every card name, which covers Personas and Epiphanies too."),
    ("EQUIPMENT", r"relic@name@", "Equipment, called relics internally."),
    ("COMBATANTS", r"char_base@name@", "Playable combatants."),
    ("FATES", r"fate@name@", "The Fates offered at the start of a run."),
    ("NODE_TYPES", r"spot_type", "Map node types, used for Route Priority."),
]
# Placeholder rows the extraction should not carry into a dropdown.
JUNK = re.compile(r"^(test|temp|dummy|sample|todo|#)", re.I)


def load_table(dump_dir):
    """Read the English localization table from an asset dump.

    Args:
        dump_dir: Path to the dump's `output` directory.

    Returns:
        A dict of localization id to text.

    Raises:
        SystemExit: When the table is missing.
    """
    path = Path(dump_dir) / "text" / "en" / "text.json"
    if not path.exists():
        raise SystemExit(f"no localization table at {path}")
    table = {}
    for row in json.loads(path.read_text(encoding="utf-8")):
        table.setdefault(row["id"], row["text"])
    return table


def collect(table, pattern):
    """Pull the distinct, usable values for one namespace.

    Args:
        table: The localization table.
        pattern: Regex matched against the start of each id.

    Returns:
        A sorted list of distinct names.
    """
    names = set()
    for key, value in table.items():
        if re.match(pattern, key):
            text = (value or "").strip()
            if text and not JUNK.match(text):
                names.add(text)
    return sorted(names)


def render(groups, dump_dir):
    """Build the source of the generated module.

    Args:
        groups: A list of `(name, values, comment)` tuples.
        dump_dir: The dump the values came from, recorded in the header.

    Returns:
        The module source as a string.
    """
    lines = [
        '"""Game entity names taken from the Global client\'s own localization table.',
        "",
        "Generated by `scripts/build_game_data.py` - do not edit by hand. Re-run it after a game patch.",
        "",
        # Forward slashes so a Windows path cannot read as an escape sequence in the generated docstring.
        f"Source: {str(dump_dir).replace(chr(92), '/')}",
        f"Generated: {date.today().isoformat()}",
        '"""',
        "",
    ]
    for name, values, comment in groups:
        lines.append(f"# {comment}")
        lines.append(f"{name} = [")
        lines.extend(f"    {value!r}," for value in values)
        lines.append("]")
        lines.append("")
    return "\n".join(lines)


def main():
    """Entry point. Writes the generated module and reports what it found.

    Returns:
        0 on success.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--dump", default=str(DEFAULT_DUMP), help="path to the asset dump's output directory")
    args = parser.parse_args()

    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    table = load_table(args.dump)
    groups = [(name, collect(table, pattern), comment) for name, pattern, comment in GROUPS]

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(render(groups, args.dump), encoding="utf-8")

    print(f"read {len(table)} localization rows from {args.dump}")
    for name, values, _ in groups:
        print(f"  {name:12} {len(values):5d}")
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
